### ISSUE TITLE
Nadchodzi Python3

### ISSUE THREAD

**Issue by xinulsw** [koduj-z-klasa/python101#2]
Ponieważ w większości wiodących dystrybucji linuksowych Python 3 jest tak czy inaczej instalowany domyślnie, pod Windowsem również nie ma problemu z jego zainstalowaniem, warto chyba przejść na tę wersję. Zmiany w kodach duże nie będą. O ile dobrze sprawdziłem, wszystkie wykorzystywane biblioteki (rozszerzenia) są pod tę wersję dostępne. Co wy na to?

**Comment by wooyek** [comment]
Można zrobić branch dla py3 i tam rozwijać przykłady do momentu jak będziemy gotowi :)

**Comment by xinulsw** [comment]
Brzmi dobrze, rozumiem, że mogę to zrobić lokalnie wg http://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging. Rozumiem, że inni będą mieli dostęp do tej gałęzi, ale co z wersją html?

**Comment by abixadamj** [comment]
W dniu 06.02.2015 o 22:26, xinulsw pisze:
>
> Ponieważ w większości wiodących dystrybucji linuksowych Python 3 jest 
> tak czy inaczej instalowany domyślnie, pod Windowsem również nie ma 
> problemu z jego zainstalowaniem, warto chyba przejść na tę wersję. 
> Zmiany w kodach duże nie będą. O ile dobrze sprawdziłem, wszystkie 
> wykorzystywane biblioteki (rozszerzenia) są pod tę wersję dostępne. Co 
> wy na to?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/koduj-z-klasa/python101/issues/2>.
>
Python 3 jest od dawna, tylko większość używa 2 ciągle w wielu miejscach.
Ja jestem za utrzymaniem zgodności z 2.

-- 
Adam Jurkiewicz
ABIX - Systemy wspomagania biznesu i edukacji.
www.abix.info.pl | www.cyfrowaszkola.waw.pl
Oferujemy szkolenia dla nauczycieli oraz wsparcie informatyczne dla szkół.
Oferujemy wsparcie systemów informatycznych i zabezpieczanie danych firm.

**Comment by wooyek** [comment]
@xinulsw jeśli zrobisz brancha i go prześlesz push'em do repo na GH to wszscy będą mieli do niego dostęp. Dokumentacji w http://koduj-z-klasa.github.io/python101/ bym nie ruszał dopuki nie będziemy mieli gotowego całego materiału w wersji py3

@abixadamj zgoda, py3 z dydaktycznego punktu widzenia nie wiele daje. Tak naprawdę to jest wybór pomiędzy tatusiem i mamusią. Za py2 przemawia fakt że jest nadal "domyślny", tj. mamy python i python3, więc nie musimy wyjaśniać pomyłek wynikających z użycia domyślnego pythona zamiast python3.

Wiele bibliotek wspiera py3, jednak głównie ze względu na prawdopodobieństwo pomyłek, fajnie by działało pod py2 a było kompatybilne z py3. Np. możemy zamiast [% do formatowania stringów](https://docs.python.org/2/library/stdtypes.html#string-formatting) używać [.format](https://docs.python.org/2/library/functions.html#format)

Można też pokusić się o użycie [six](http://pythonhosted.org/six/), ale to wprowadza kolejne warstwy komplikacji które będą niezrozumiałe, a z punktu widzenia celu naszych materiałów chyba nie warto zbytnio komplikować.

…nie mniej jednak nie widzę przeszkód — prócz pracochłonnością — by mieć wersję materiałów py3 obok domyślnej :)

**Comment by xinulsw** [comment]
Oczywiście nic na siłę, domyślnie może być 2. Niemniej wersję 3 też bym zrobił, bo wcześniej czy później ona stanie się domyślna tak jak np. w Archu. Zrobię więc lokalnie gałąź py3, a później będą ją sukcesywnie aktuaizował.
@wooyek Czy dałoby się osbno podpiąć gałąź py3 pod redthedocs.org?

**Comment by wooyek** [comment]
@xinulsw załóż konto na https://readthedocs.org/accounts/signup/ i nadam tobie prawa admina. Założyłem też branch py3, bo żeby się pojawiło w RTD to trzeba mieć co podpiąć ;)

**Comment by wooyek** [comment]
Już się buduje :)

http://python101.readthedocs.org/pl/py3/

**Comment by xinulsw** [comment]
Szybszy niż błyskawica :-) jesteś. Mam konto na redthedocs: xinulsw@gmail.com. Co do wyglądu, moim zdaniem nie jest źle. Poza tym w końcu chyba wydadzą stabilną wersję Sphinxa... Rozumiem, że pozostaje mi tylko podpiąć się pod gałąź py3 i działać.

**Comment by wooyek** [comment]
Tymczasem zamykam by nie wisiało, jak wrócimy do tematu to się ew. otworzy.
