### ISSUE TITLE
Struktura i kategoryzacja dokumentacji

### ISSUE THREAD

**Issue by xinulsw** [koduj-z-klasa/python101#3]
Udało mi się uzyskać dzięki wprowadzeniu loklanego spisu treści i jQuery 3-poziomowe menu w nawigacji. Efekt, mam nadzieję, zadowalający. Skategoryzowałem więc scenariusze, żeby menu było bardziej przejrzyste. Mam zamiar stworzyć jeszcze kategorie "Podstawy Pythona" i wrzucić tam scenariusze początkowe. Co Wy na to?

**Comment by wooyek** [comment]
![](http://www.sherv.net/cm/emoticons/hand-gestures/praising-the-lord-smiley-emoticon.gif)

**Comment by xinulsw** [comment]
Thx :-)

**Comment by wooyek** [comment]
Done? Zamykamy issue?

**Comment by xinulsw** [comment]
Tak :-)
