### ISSUE TITLE
Wygaszenie koduj-z-klasa.github.io i przejście na RTD

### ISSUE THREAD

**Issue by wooyek** [koduj-z-klasa/python101#4]
Wygląda na to że mamy release [Sphinx'a](http://sphinx-doc.org/) 1.3.1 i Read The Docs może już odpowiadać za budowanie dokumentacji.

@xinulsw Czy masz coś przeciw wy przejść zupełnie na http://python101.readthedocs.org/?

**Comment by xinulsw** [comment]
Jasne że nie, rozumiem, że od teraz nie trzeba ręcznie budować wersji html w python101-gh-pages?

**Comment by xinulsw** [comment]
Przed chwilą sprawdzałem i wersja na readthedocs.org odbiega trochę od wersji generowanej ręcznie.

**Comment by wooyek** [comment]
Tak, wielke ułatwienie :)

Ale, chciałbym mieć pewność ze automatycznie budowana dokumentacja nie jest
gorsza. Możesz rzucić okiem na to co dobudowywałeś czy nie zniknęło w RTD?

**Comment by xinulsw** [comment]
Był problem z numeracją zagnieżdżonych spisów treści, ale poprawiłem to. Pozostaje wyświetlanie fragmentów kodu inline - są renderowane w szarej ramce czarną czcionką na białym tle, w dokumentacji lokalnej czcionka jest czerwona. Poza tym wydaje mi się, że nie wszystkie skrypty z katalogu _static są includowane na rtd, poza custom.js. Tego jednak na razie nie potrzebujemy...
