### ISSUE TITLE
Wersja Django 1.8

### ISSUE THREAD

**Issue by xinulsw** [koduj-z-klasa/python101#5]
@wooyek Widzę, że się wziąłeś za ostre przeglądanie materiałów, zabawne, że ja też... ale nie o tym chciałem.

Proponuję rekomendowanie Django w wersji 1.8 jako nowej stabilnej. Zaktualizowałbym scenariusz o użycie virtualenv dj8; pip install Django==1.8 - tak żeby nawet na systemach, gdzie Django jest jeszcze w wersji 1.6 (np. Xubuntu 14.04) można było robić scenariusz. Co wy na to?

**Comment by wooyek** [comment]
Jestem za. Django warto pokazywać ostatnie, bo ostatnio dużo się zmieniło.

Proponuję dalsze dyskusje ciągnąć już na forum. Tutaj poza nami nikt nie zagląda, a ciągle liczę że ktoś się do nas przyłączy. 

Chyba że masz inne zdanie: http://discourse.kodujzklasa.pl/t/gdzie-omawiamy-problemy-python101-tutaj-czy-na-githubie/17

Tam też wrzucaj następne pytania, które ew. kierowałbyś do mnie mailem, zostanie ślad i może odpowiedzi komuś się przydadzą :D

**Comment by xinulsw** [comment]
Ok :-)
